version: 2
updates:
  - package-ecosystem: pip
    directory: /substrate_inheritance
    target-branch: substrate-inheritance
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: github-actions
    directory: /
    target-branch: substrate-inheritance
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: ci-deps
      include: scope
